version: "3.5"
services:
    api:
        image: "node:10.12.0-alpine"
        volumes:
            - "./app:/app"
        working_dir: "/app"
        env_file:
            - "./config/config.env"
            - "./config/secrets.env"
        ports:
            - "3001:3000"
        entrypoint: "npm start -- --max-old-space-size=4096"

    db:
        image: "mysql:8.0.3"
        env_file:
            - "./config/config.env"
            - "./config/secrets.env"
        ports:
            - "3306:3306"
        volumes:
            - "./db-data:/var/lib/mysql"
